version: 2
updates:
- package-ecosystem: "npm"
  directory: "/"
  schedule:
    interval: weekly
    time: "21:00"
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: weekly
